services:
  - type: web
    name: carbonbridge-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    region: oregon

    buildCommand: ""

    startCommand: ""

    preDeployCommand: "python manage.py migrate --noinput"

    healthCheckPath: /api/health/

    envVars:
      - key: SECRET_KEY
        generateValue: true

      - key: DEBUG
        value: "False"

      - key: ALLOWED_HOSTS
        value: "carbonbridge-api.onrender.com"

      - key: DATABASE_URL
        fromDatabase:
          name: carbonbridge-db
          property: connectionString

      - key: CORS_ALLOWED_ORIGINS
        value: "https://carbonbridge.vercel.app"

      - key: CORS_ALLOW_ALL_ORIGINS
        value: "False"

      - key: GUNICORN_WORKERS
        value: "2"

      - key: GUNICORN_THREADS
        value: "2"

databases:
  - name: carbonbridge-db
    plan: free
    databaseName: carbonbridge
    user: carbonbridge_user
    region: oregon
