# Generated by Django 5.0.14 on 2026-05-24 22:02

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(db_index=True, help_text='Must match NormalizedRecord.activity_type values.', max_length=50)),
                ('unit', models.CharField(help_text='Normalised unit this factor applies to (L, kWh, km, night, kg, m3).', max_length=20)),
                ('factor_kgco2e', models.DecimalField(decimal_places=8, help_text='kgCO₂e emitted per 1 unit of activity.', max_digits=18)),
                ('region', models.CharField(choices=[('GLOBAL', 'Global (default)'), ('UK', 'United Kingdom'), ('EU', 'European Union'), ('US', 'United States'), ('AU', 'Australia'), ('DE', 'Germany')], db_index=True, default='GLOBAL', max_length=10)),
                ('source', models.CharField(default='DEFRA 2023', help_text='Publication or standard this factor originates from.', max_length=255)),
                ('valid_from', models.DateField(default=django.utils.timezone.now, help_text='First date this factor is applicable.')),
                ('valid_to', models.DateField(blank=True, help_text='Last date this factor is applicable (null = still current).', null=True)),
                ('notes', models.TextField(blank=True, help_text='Methodology notes or sub-category details.')),
            ],
            options={
                'verbose_name': 'Emission Factor',
                'verbose_name_plural': 'Emission Factors',
                'ordering': ['activity_type', 'region', '-valid_from'],
                'indexes': [models.Index(fields=['activity_type', 'unit', 'region', 'valid_from'], name='emissions_e_activit_47eee8_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating whether this record has been soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp of when this record was soft-deleted.', null=True)),
                ('factor_snapshot_kgco2e', models.DecimalField(blank=True, decimal_places=8, help_text='The exact factor value used at calculation time.', max_digits=18, null=True)),
                ('activity_quantity', models.DecimalField(decimal_places=6, help_text='NormalizedRecord.normalized_value at calculation time.', max_digits=18)),
                ('activity_unit', models.CharField(help_text='NormalizedRecord.normalized_unit at calculation time.', max_length=20)),
                ('emission_kgco2e', models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Total GHG output in kilograms of CO₂ equivalent.', max_digits=18)),
                ('emission_tco2e', models.DecimalField(decimal_places=9, default=Decimal('0'), help_text='Total GHG output in metric tonnes of CO₂ equivalent (= kgCO₂e / 1000).', max_digits=18)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Calculation'), ('CALCULATED', 'Successfully Calculated'), ('FACTOR_MISSING', 'No Matching Factor Found'), ('ERROR', 'Calculation Error')], db_index=True, default='PENDING', max_length=20)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('calculation_notes', models.TextField(blank=True, help_text='Any warnings, fallback decisions, or edge-case notes.')),
                ('emission_factor', models.ForeignKey(blank=True, help_text='Factor used at calculation time (null if no factor found).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emission_records', to='emissions.emissionfactor')),
                ('normalized_record', models.OneToOneField(help_text='The source normalized activity this calculation was derived from.', on_delete=django.db.models.deletion.CASCADE, related_name='emission_record', to='core.normalizedrecord')),
            ],
            options={
                'verbose_name': 'Emission Record',
                'verbose_name_plural': 'Emission Records',
                'ordering': ['-calculated_at'],
            },
        ),
    ]
