# Generated by Django 5.0.14 on 2026-05-24 20:13

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating whether this record has been soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp of when this record was soft-deleted.', null=True)),
                ('name', models.CharField(help_text='Enterprise or subsidiary legal name.', max_length=255)),
                ('slug', models.SlugField(help_text='Unique URL-friendly identifier.', max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating whether this record has been soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp of when this record was soft-deleted.', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('tenant', models.ForeignKey(blank=True, help_text='The tenant this user belongs to. Leave empty for global system administrators.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.tenant')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating whether this record has been soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp of when this record was soft-deleted.', null=True)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP ERP System'), ('UTILITY', 'Utility Invoices'), ('TRAVEL', 'Corporate Travel Tracker')], max_length=20)),
                ('activity_type', models.CharField(choices=[('fuel', 'Fuel Consumption'), ('procurement', 'Procured Goods & Services'), ('electricity', 'Purchased Electricity'), ('flight', 'Business Flight'), ('hotel', 'Hotel Stays'), ('ground_transport', 'Ground Transportation')], max_length=30)),
                ('scope', models.CharField(choices=[('Scope1', 'Scope 1 (Direct Emissions)'), ('Scope2', 'Scope 2 (Indirect Purchased Energy)'), ('Scope3', 'Scope 3 (Other Indirect Value Chain)')], max_length=10)),
                ('original_unit', models.CharField(help_text='E.g., Gallons, kWh, Passenger-Kilometers.', max_length=50)),
                ('normalized_unit', models.CharField(help_text='Standardized unit (e.g., Liters, kWh, kgCO2e).', max_length=50)),
                ('original_value', models.DecimalField(decimal_places=6, help_text='Original raw numeric value.', max_digits=18)),
                ('normalized_value', models.DecimalField(decimal_places=6, help_text='Value converted to normalized unit scale.', max_digits=18)),
                ('activity_date', models.DateField(db_index=True, help_text='Date when physical carbon emission activity occurred.')),
                ('confidence_score', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='AI/heuristic accuracy confidence (0.0000 to 1.0000).', max_digits=5)),
                ('suspicious_flag', models.BooleanField(default=False, help_text='Flagged automatically if metric deviates abnormally from baseline.')),
                ('approval_status', models.CharField(choices=[('Pending', 'Pending Auditor Verification'), ('Approved', 'Approved & Sealed'), ('Rejected', 'Rejected')], db_index=True, default='Pending', max_length=20)),
                ('source_reference', models.CharField(blank=True, help_text='Upstream reference index (e.g. invoice id, transaction slug).', max_length=255, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_records', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Normalized Record',
                'verbose_name_plural': 'Normalized Records',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='E.g., CREATE, UPDATE, DELETE, APPROVE, REJECT', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('old_values', models.JSONField(blank=True, help_text='State snapshot prior to transformation.', null=True)),
                ('new_values', models.JSONField(blank=True, help_text='State snapshot following transformation.', null=True)),
                ('user', models.ForeignKey(blank=True, help_text='Account that initiated the change.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.normalizedrecord')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating whether this record has been soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp of when this record was soft-deleted.', null=True)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP ERP System'), ('UTILITY', 'Utility Invoices'), ('TRAVEL', 'Corporate Travel Tracker')], help_text='Category of upstream supplier system.', max_length=20)),
                ('name', models.CharField(help_text='User-friendly name of the pipeline.', max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='core.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating whether this record has been soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp of when this record was soft-deleted.', null=True)),
                ('upload_timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Processing'), ('PARSING', 'Currently Parsing'), ('COMPLETED', 'Successfully Completed'), ('FAILED', 'Ingestion Failed')], default='PENDING', max_length=20)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.datasource')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Upload Batch',
                'verbose_name_plural': 'Upload Batches',
            },
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating whether this record has been soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp of when this record was soft-deleted.', null=True)),
                ('original_payload_json', models.JSONField(help_text='Exact raw JSON imported from third-party vendor.')),
                ('parsing_status', models.CharField(choices=[('PENDING', 'Pending Extraction'), ('PARSED', 'Successfully Parsed'), ('FAILED', 'Parsing Failed')], default='PENDING', max_length=20)),
                ('parsing_errors', models.JSONField(blank=True, help_text='Diagnostic message log if extraction failed.', null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='core.uploadbatch')),
            ],
            options={
                'verbose_name': 'Raw Record',
                'verbose_name_plural': 'Raw Records',
            },
        ),
    ]
