# Generated by Django 5.0.14 on 2026-05-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['tenant', 'approval_status'], name='core_normal_tenant__d0b398_idx'),
        ),
    ]
